### ISSUE TITLE
Could not parse 'quorum-aws/stack.yaml':

### ISSUE THREAD

**Issue by rossrollin** [jpmorganchase/quorum-aws#12]
Hi,

It seems the haskell-stack doesn't parse the stack.yaml file, it may need a refactor. I am trying to use an older version of the haskell stack as a workaround.

**Comment by fixanoid** [comment]
This project and most of the dependencies are a bit dated at this point and are unlikely to be updated. At the moment, we advise users to switch to jpmorganchase/quorum-cloud and we are in progress of creating our own terraform quorum provider.
