### ISSUE TITLE
Error while running terraform/demo

### ISSUE THREAD

**Issue by tblakers** [jpmorganchase/quorum-aws#3]
If I run `./bin/demo apply` with Terraform 0.11.3, I get the following error:

> (snip)
> 2018/03/05 11:58:03 [ERROR] root: eval: *terraform.EvalWriteOutput, err: element: element() may not be used with an empty list in:
> ${element(aws_eip_association.quorum_eip_association.*.public_ip, 0)}
2018/03/05 11:58:03 [ERROR] root: eval: *terraform.EvalOpFilter, err: element: element() may not be used with an empty list in:
> ${element(aws_eip_association.quorum_eip_association.*.public_ip, 0)}
2018/03/05 11:58:03 [ERROR] root: eval: *terraform.EvalSequence, err: element: element() may not be used with an empty list in:
> ${element(aws_eip_association.quorum_eip_association.*.public_ip, 0)}
data.aws_ami.ubuntu: Refreshing state...
>
> Error: Error refreshing state: 1 error(s) occurred:
>
>* output.eip: element: element() may not be used with an empty list in:
>
>${element(aws_eip_association.quorum_eip_association.*.public_ip, 0)}`

**Comment by tblakers** [comment]
Appears to be related to the differing needs of "demo" and "multi region". For demo, I was able to work around as follows:

In terraform/output.tf, comment out all "geth" outputs except the first. e.g.

> //output "geth2" { value = "${ var.multi_region ? "" : aws_instance.quorum.1.public_ip }" }
> //output "geth3" { value = "${ var.multi_region ? "" : aws_instance.quorum.2.public_ip }" }

In terraform/output.tf, comment out the multi region lines:

>//# Output for multi-region IP
> //output "eip" {
> //  value = "${element(aws_eip_association.quorum_eip_association.*.public_ip, 0)}"
> //}
> //output "all_eips" {
> //  value = ["${aws_eip_association.quorum_eip_association.*.public_ip}"]
> //}

**Comment by fixanoid** [comment]
Removed from master.
